### ISSUE TITLE
Log4j 1.x and Log4j2 dependencies should not be included in runtime dependencies

### ISSUE THREAD

**Issue by dagansandler** [reportportal/logger-java-log4j#32]
The dependencies today include both Log4j1.2 and Log4j2 as `api` dependencies:
https://github.com/reportportal/logger-java-log4j/blob/2d74a8738240a98b092618ba7be6f0e54bed3cd3/build.gradle#L34

This can cause severe issues when running because clients may pull both of these packages which will cause conflicts (SPI mechanisms could inadvertently initialize Log4j2 while a user is expecting to use Log4j1.2.

I think that Log4j dependencies should be declared as `compileOnly` or `compileOnlyApi`:
https://docs.gradle.org/6.7/release-notes.html#new-dependency-management-features

And the user should be responsible to make sure the correct runtime dependency is present.

**Comment by HardNorth** [comment]
@dagansandler, short answer no. And this is not a point to discuss anymore.

It used to be declared as `implementation` for version 5.0.2. Unfortunately our users are not so technically experienced to decide which library version to use and how to configure build system correctly. That leads to such issues like that: https://github.com/reportportal/logger-java-log4j/issues/31

This repeated from agent to agent and brought me tons of similar questions in our sack channels and in private messages. So I reverted everything back and won't apply this again until we have some amount of volunteers, who will answer all of these questions instead of me.

**Comment by dagansandler** [comment]
I don't think that `implementation` is correct either.

Currently, configuration OOTB is incorrect.
I'm not sure that #31 was directly related to this either.

Bringing these two dependencies together on classpath causes all sort of different trouble, especially when working with SPI, Spring, SLF4J, or anything that tries to automatically decide what logging framework to use.

If there's no intention to make them `compileOnly` and leave it up to the user to import their correct logging framework, I suggest to split this module completely, similarly to how the `logback` module is separated.

**Comment by HardNorth** [comment]
Oh, you offer me to use a feature which was released a month ago. I'm not sure I'm ready to migrate on gradle 6.7. Usually it's a huge piece of work because new gradle versions often incompatible with previous versions and it necessary to update build scripts for the whole project. This is ridiculously time-spending now, people wants me to implement JBehave, Spock and Android agents.

I don't know why Log4j loggers were implemented in a single project. I don't like it either. But refactoring them into two separate projects, update the whole technical documentation, build script refactoring and other such activities are far behind current priorities.

And the issues you describing is solvable just by a single exclusion as far as I understand.
