### ISSUE TITLE
Improve throwable logging (undeadable stack-trace)

### ISSUE THREAD

**Issue by daroshchanka** [reportportal/logger-java-log4j#6]
We use log4j.
```
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>4.0.1</version>
        </dependency>
```

log4j.properties
```
log4j.rootLogger=DEBUG, rp
log4j.appender.rp=com.epam.ta.reportportal.log4j.appender.ReportPortalAppender
log4j.appender.rp.layout=org.apache.log4j.PatternLayout
log4j.appender.rp.layout.ConversionPattern = %d  %-5p  - %m %n
```

Log exceptions:
(groovy example)
```
@Test
    void logExceptionTest(){
        log.error(new RuntimeException('message'))
    }
```

Actual:
![image](https://user-images.githubusercontent.com/28945630/44411813-0db9ca00-a570-11e8-81f3-bd4199f1451f.png)

Expected:
![image](https://user-images.githubusercontent.com/28945630/44412071-af411b80-a570-11e8-84ec-a4545d2cd0e6.png)

We suggest adding a new line for each stack-trace line.

**Comment by dagansandler** [comment]
+1

**Comment by dagansandler** [comment]
I believe I found the issue, which is in the `com.epam.ta.reportportal.log4j.appender.ReportPortalAppender` class

Specifically lines 74-76 which appends the stack trace lines:
```java
for (String oneLine : event.getThrowableStrRep()) {
   throwable.append(oneLine);
}
```

This can be fixed in one of two ways I think:
1. add a `append("\n")` call inside the loop - tested this and it seems to work.
2. replace the loop altogether with a call to `rp.com.google.common.base.Throwables.getStackTraceAsString(event.getThrowableInfo().getThrowable())` which will return a formatted stack trace string (This is actually how it's done in the agent-java-testng itself)

**Comment by DzmitryHumianiuk** [comment]
@daroshchanka @dagansandler second approach is preferable.
Please send us pull request

**Comment by DzmitryHumianiuk** [comment]
@daroshchanka @dagansandler merged

**Comment by dagansandler** [comment]
any ETA on when will a release with this fix is going to ship?

**Comment by DzmitryHumianiuk** [comment]
@dagansandler @pbortnik and @avarabyeu are on vacation till mid-end of Sep.
if it's not configured for auto build, then only after vacation

**Comment by dagansandler** [comment]
@DzmitryHumianiuk 3 months later there is still no release with the fix...
